### ISSUE TITLE
Title the Untitled Python Project

### ISSUE THREAD

**Issue by cocomittens** [noisebridge/UntitledPythonProject#1]
Come up with a name

**Comment by audiodude** [comment]
Awesome, let's come up with a name! I'm going to post each one as it's own comment so we can reply with emoji!

**Comment by audiodude** [comment]
Noisebridge Nexus

**Comment by audiodude** [comment]
NoiseMix

**Comment by audiodude** [comment]
MixBridge

**Comment by audiodude** [comment]
CultureBug/MediaBug

**Comment by audiodude** [comment]
NB MediaBot

**Comment by audiodude** [comment]
The Noise Picker (goof on nose picker)

**Comment by elimisteve** [comment]
Titled Python Project

**Comment by cocomittens** [comment]
Noisewave

**Comment by cocomittens** [comment]
NoiseLink

**Comment by cocomittens** [comment]
MediaBridge

**Comment by Inokyo** [comment]
ReBridge

**Comment by siddz415** [comment]
Cinematch

**Comment by siddz415** [comment]
Cinebridge

**Comment by audiodude** [comment]
Please everyone vote on a name so we can decide on one!!

:heavy_check_mark: :+1:

**Comment by audiodude** [comment]
By consensus, we have decided on.....

MediaBridge!
