### ISSUE TITLE
Create SQL schema for movies

### ISSUE THREAD

**Issue by audiodude** [noisebridge/UntitledPythonProject#4]
Something along the lines of :

```
CREATE TABLE movies (
  id NOT NULL primary key auto_increment,
  title NOT NULL varchar(512),
 ....
}
```

etc.

This is not needed if we end up using MongoDB or another no-SQL solution.

**Comment by audiodude** [comment]
Note: we might not be using a relational/SQL database ,see #3. However, we should definitely be thinking about what features/fields we want to store for each movie, probably based on what's available in Wikidata: https://www.wikidata.org/wiki/Q83495 (note not all movies will have the same fields in Wikidata).

**Comment by cocomittens** [comment]
Based on wikidata Im guessing we probably want at least these? (May not need data types explicitly but this is what Id assume theyd be)

title: string,
description: string,
subjects (main subject): string[],
genre: string[],
rating: float

**Comment by siddz415** [comment]
We should use MongoDB
            "_id": "",
            "title": "",
            "release_year": ,
            "genres": [""],
            "director": "",
            "cast": [""],
            "wikidata_id": ""
